name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy over SSH
        run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            set -e
            cd /opt/streamlit/app
            git fetch --all
            git reset --hard origin/main

            # usa o pip DA VENV diretamente (sem precisar de "source")
            /opt/streamlit/app/.venv/bin/pip install -r requirements.txt

            sudo systemctl restart streamlit
            '
